server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH:}
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DATABASE:pgazienda}
      
  mail:
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:}
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    protocol: ${MAIL_PROTOCOL:smtp}
    from: ${MAIL_FROM:no-reply@playngo.it}
    baseurl: ${MAIL_BASEURL:http://localhost}
    properties:
      mail:
        smtps:
          localhost: ${MAIL_LOCALHOST:}
  messages:
    basename: i18n/messages

  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ${AAC_CLIENT_ID:}
            client-secret: ${AAC_CLIENT_SECRET:}
            authorization-grant-type: client_credentials
        provider:
          custom:
            token-uri: ${AAC_TOKEN_URI:https://aac.platform.smartcommunitylab.it/oauth/token}
            jwk-set-uri: ${AAC_JWK_URI:https://aac.platform.smartcommunitylab.it/jwk}
            issuer-uri: ${AAC_ISSUER_URI:https://aac.platform.smartcommunitylab.it}
            user-info-uri: ${SECURITY_EXT_USERINFO_ENDPOINT:https://aac.platform.smartcommunitylab.it/userinfo}

management:
   server:
      port: ${MANAGEMENT_PORT:7878}
   endpoints:
      web:
         base-path: /
         exposure:
            include: health,info,metrics

# SWAGGER
swagger:
   title: Play&Go Aziende API
   description: API for the company management and user association
   version: 1.0.0
   license: Apache License, Version 2.0
   licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
   contact:
      name: Smart Community Lab
      url: www.smartcommunitylab.it
      email: info@smartcommunitylab.it

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}

app:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: ${SECURITY_SECRET:bgYh3rbvGzbJKK/q7k624Ct360QuA4IHHO8jBtMUKA/spqu+BMLkktWpiQuBMXuoVxBYOUwWnBvLXnizzrhKFyJkX9gf9gU6+L8tJl6D1VjAwh8w/iwqiubqmmMSSRxdmu7rmFWLlSi3HpumEfsIzagI2TiPI2U2pCn27vn2TAthiUXELXusVYe3r9awz2DQP/V10yi3j9AIh0Gslz89yUjY6tmrQ8RcJSApvo4FGBdK1EzZU/6CZaEFvmPQEx3I8TG26Y8pVqfcuR+OELhLQ2iOfP5ZlwQiom4UmkNdbMh4ZLyfSN0C9anZojYnpSBym6N8XOQo+7Ueqgpm0w0dFw==}
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
    ext:
      player-field: ${SECURITY_EXT_USERINFO_PLAYER_FIELD:sub}
      username-field: ${SECURITY_EXT_USERINFO_USERNAME_FIELD:preferred_username}
      name-field: ${SECURITY_EXT_USERINFO_NAME_FIELD:given_name}
      surname-field: ${SECURITY_EXT_USERINFO_SURNAME_FIELD:family_name}
      domain: ${SECURITY_EXT_USERINFO_DOMAIN:}

  legacyCampaign: ferrara_bike2work
  engineEndpoint: ${ENGINE_ENDPOINT:https://backenddev.playngo.it/playandgo/}
      
